### ISSUE TITLE
Two undefined names

### ISSUE THREAD

**Issue by cclauss** [monoxgas/sRDI#1]
Python 3 removed `file()`.

flake8 testing of https://github.com/monoxgas/sRDI on Python 3.6.2

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./Python/pefile.py:928:14: F821 undefined name 'exceptions'
						except exceptions.ValueError as e:
             ^
./Python/peutils.py:405:14: F821 undefined name 'file'
					sig_f = file( filename, 'rt' )
             ^
```

**Comment by monoxgas** [comment]
This section of the code is taken from https://github.com/erocarrera/pefile

Maybe simply change to an external dependency.

**Comment by cclauss** [comment]
Yes.  These issues seem to be fixed in https://github.com/erocarrera/pefile
