### ISSUE TITLE
NativeLoader uses hard coded DLL path instead of argv[1]

### ISSUE THREAD

**Issue by cetfor** [monoxgas/sRDI#18]
Hey, great project!

I just wanted to note that the native loader is set to use a hard coded dll path: "C:\\Users\\Nick\\Documents\\Projects\\Throwback\\Throwback2.5\\bin\\Persistence_InstallUtil_x64.dll"

Changing this string to argv[1] allows the NativeLoader to work as expected.  This might have just been a commit mistake from testing. Just wanted to point it out. Thanks!

Source link:
https://github.com/monoxgas/sRDI/blob/9d6933cfa40e636de3bec1e5b1b49766f7b3be39/Native/Loader.cpp#L348

**Comment by monoxgas** [comment]
Hey nice catch, I've pushed a fix for this in master :)

If only I could use Git properly...
